### ISSUE TITLE
`DeFiCh/ain:2.x.x` Loan RPCs implementation

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#488]
Similar to https://github.com/DeFiCh/jellyfish/issues/48, this tracks all the RPC methods and categories being implemented in `jellyfish-api-core`. Please tag and update this if you are working on a feature.

As a final docker build is not produced please use the latest `1.9.x` docker builds for your `testcontainers`, https://github.com/DeFiCh/jellyfish/pull/184 for more information on how to set custom image doing development.

### `rpc_loan.cpp`
- [x] createLoanScheme @jingyi2811 #520 
- [x] updateLoanScheme @jingyi2811 #530 
- [x] destroyLoanScheme @jingyi2811  #526 
- [x] setDefaultLoanScheme @jingyi2811  #554 
- [x] listLoanSchemes @jingyi2811  #524 
- [x] getLoanScheme @jingyi2811 #638 
- [x] setCollateralToken @jingyi2811  #537
- [x] getCollateralToken @jingyi2811  #546
- [x] listCollateralTokens @jingyi2811  #551
- [x] setLoanToken @jingyi2811  #568 
- [x] updateLoanToken @jingyi2811  #570 
- [x] getloantoken @surangap #758 
- [x] listLoanTokens @jingyi2811  #571 
- [x] takeLoan @canonbrother #661 
- [x] getLoanInfo @ivan-zynesis ~~#654~~ update: DeFiChain almost reworked the RPC, opened PR is invalid
- [x] loanPayBack @canonbrother #699 
- [x] getInterest @canonbrother #678
- [x] ~~getCollateralPrice~~

### `rpc_vault.cpp`
- [x] createVault @surangap  #553 
- [x] getVault  @surangap #569 
- [x] listVaults  @surangap #552 
- [x] updateVault @jingyi2811 #698 
- [x] depositToVault @canonbrother #661 
- [x] withdrawFromVault @ivan-zynesis #741  
- [x] closevault @jingyi2811 #730 
- [x] auctionBid @canonbrother #677 
- [x] listAuctions @jingyi2811 #695
- [x] listAuctionHistory @jingyi2811 #787 
- [ ] listVaultHistory @jingyi2811 #834
- [x] estimateloan @cwkang1998 #1347
- [x] estimatecollateral @cwkang1998 #1350 
- [x] estimatevault @cwkang1998 #1354 

### `rpc_oracles.cpp`
- [x] getfixedintervalprice @canonbrother  #760 
- [x] listfixedintervalprices @canonbrother #760 

### `rpc_poolpair.cpp`
- [x] compositeswap @ivan-zynesis #776

### `mn_rpc.cpp`
- [x] setGovHeight @ivan-zynesis #789
- [x] listGovs@ivan-zynesis #789
- [x] ~~getGov~~ @ivan-zynesis  #794 defid reverted

---
Known flaky test for investigation:
~~https://github.com/DeFiCh/jellyfish/pull/752/checks?check_run_id=3930860973#step:5:3610~~
